# -*- mode: ruby -*-
# vi: set ft=ruby :

## my "vagrant-libvirt" bridge network is 192.168.121.0/24, modify it as you please
NETWORK_ID = "192.168."
SUBNET_ID ="121."

# bridge to my laptop's ethernet card
INT_CARD="br-lenovo-usb"

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2004"
  
  HOST_ID = "10"
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu"
    #ubuntu.vm.synced_folder ".", "/vagrant", type: rsync
    #ubuntu.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    ubuntu.vm.network "private_network", ip: NETWORK_ID + SUBNET_ID + HOST_ID, auto_config: false
    ubuntu.vm.network "public_network", dev: INT_CARD, mode: "bridge", type: "bridge"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = 384
      vb.cpus = 2
    end
    ubuntu.vm.provider "libvirt" do |lv|
      lv.memory = 384
      lv.cpus = 2
    end
  end

  HOST_ID = "20"
  config.vm.define "apache" do |apache|
    apache.vm.hostname = "apache"
    #apache.vm.synced_folder ".", "/vagrant", type: rsync
    #apache.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    apache.vm.network "private_network", ip: NETWORK_ID + SUBNET_ID + HOST_ID, auto_config: false
    apache.vm.network "public_network", dev: INT_CARD, mode: "bridge", type: "bridge"
    apache.vm.provider "virtualbox" do |vb|
      vb.memory = 384
      vb.cpus = 2
    end
    apache.vm.provider "libvirt" do |lv|
      lv.memory = 384
      lv.cpus = 2
    end
    apache.vm.provision "shell", path: "../../../provision/shell/apt/apache.sh"
  end

  HOST_ID = "30"
  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginx"
    #nginx.vm.synced_folder ".", "/vagrant", type: rsync
    #nginx.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    nginx.vm.network "private_network", ip: NETWORK_ID + SUBNET_ID + HOST_ID, auto_config: false
    nginx.vm.network "public_network", dev: INT_CARD, mode: "bridge", type: "bridge"
    nginx.vm.provider "virtualbox" do |vb|
      vb.memory = 384
      vb.cpus = 2
    end
    nginx.vm.provider "libvirt" do |lv|
      lv.memory = 384
      lv.cpus = 2
    end
    nginx.vm.provision "shell", path: "../../../provision/shell/apt/nginx.sh"
  end

  HOST_ID = "40"
  config.vm.define "lighttpd" do |lighttpd|
    lighttpd.vm.hostname = "lighttpd"
    #lighttpd.vm.synced_folder ".", "/vagrant", type: rsync
    #lighttpd.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    lighttpd.vm.network "private_network", ip: NETWORK_ID + SUBNET_ID + HOST_ID, auto_config: false
    lighttpd.vm.network "public_network", dev: INT_CARD, mode: "bridge", type: "bridge"
    lighttpd.vm.provider "virtualbox" do |vb|
      vb.memory = 384
      vb.cpus = 2
    end
    lighttpd.vm.provider "libvirt" do |lv|
      lv.memory = 384
      lv.cpus = 2
    end
    lighttpd.vm.provision "shell", path: "../../../provision/shell/apt/lighttpd.sh"
  end

  HOST_ID = "50"
  MYSQL_PWD="pass"
  config.vm.define "docker-lamp" do |lamp|
    lamp.vm.hostname = "docker-lamp"
    #lamp.vm.synced_folder ".", "/vagrant", type: rsync
    #lamp.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    lamp.vm.network "private_network", ip: NETWORK_ID + SUBNET_ID + HOST_ID, auto_config: false
    lamp.vm.network "public_network", dev: INT_CARD, mode: "bridge", type: "bridge"
    lamp.vm.provider "virtualbox" do |vb|
      vb.memory = 384
      vb.cpus = 2
    end
    lamp.vm.provider "libvirt" do |lv|
      lv.memory = 384
      lv.cpus = 2
    end
    lamp.vm.provision "docker" do |d|
      d.run "mysql",
        args: "-e MYSQL_ROOT_PASSWORD=" + MYSQL_PWD
      d.run "phpmyadmin",
        args: "-p 8080:80 --link mysql:db"
    end
  end

end
